  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Electronic Signature Policy</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/i9.css" rel="stylesheet">


  </head>
<div >
	<form class="aesform" method="post" action="" >
		<div style="text-align;justify;">
			<div class="row" style="text-align:center;">
				<h1 >Electronic Signature Policy</h1>
			</div>
			<br />
			<div class="row">
				<div class="heading" >Policy:</div>
				<div class="paragraph">The purpose of this policy is to utilize current technology in the provision of patient care.</div>
			</div>
			<br />
			<div class="row">
				<div class="paragraph">(<?php echo $discipline_name?>) employees, contractors and physicians may use electronic signatures on authorized computer generated documentation. An electronic signature shall serve as authentication on Patient Record Documents AND Human Resource Documents generated in an electronic system.</div>
			</div>
			
			<br />
			<div class="row">
				<div class="heading" >Procedure:</div>
				<div class="paragraph">
				
					<ol>
						<li><?php echo $discipline_name?> employees, contractors and physicians may create patient documentation via computer system.</li>
						<li>Each user shall be provided training on the policies and procedures of electronic signatures.</li>
						<li>For the purpose of the electronic medical record, and documents printed from the electronic medical record, the employee’s use of a signature password after authenticating with their system password shall serve as their legal signature.</li>
						<li>A signature password shall be generated by the employee, contractor or physician and shall only be accessible to them.</li>
						<li>
							Each user shall be required to change their password
							<ul>
								<li>upon a password being reset by an agency administrator</li>
								<li>every <60> days</li>
								<li>at the employee’s discretion after prior authorization from the administrator</li>
							</ul>
						</li>
						<li>Each user must keep their login username/ password and signature password secret; and only administrators may reset a user password.</li>
						<li>If a signature password must be reset, then the employee, contractor or physician must submit a request to the agency with authentication information to reset the signature password.</li>
						<li>Each user shall report a breach of password or unknown application of electronic signature to appropriate administrative staff.</li>
						<li>After clinical review each document submitted by a clinician shall be returned to the clinician for electronic signature. When the document is signed, it shall at that point become part of the electronic medical record.</li>
						<li>
							Each employee, contractor or physician documenting electronically in the electronic medical record shall be required to sign an electronic signature authenticity agreement. The agreement shall require that they:
							<ul>
								<li>Never share their login username / password or their signature password with anyone.</li>
								<li>
									Exit the electronic medical record software at the end of each working day, and when the computer shall
									not be used for clinical documentation.
								</li>
								<li>Review all documentation prior to submission.</li>
							</ul>
						
						</li>
						<li>Each employee shall review documentation and make needed corrections to documents returned by a Case Manager.</li>
						<li>In the event of a system outage that prohibits electronically signed documents, documents shall be produced manually.</li>
						<li>Upon termination or employment; the administrator shall immediately disable the employee, contractor or physician credentials needed to access all organizational electronic medical records.</li>
					</ol>
				
				</div>
			</div>
			<br />
			<br />
			<br />
			<div class="row">
				<h1><?php echo $discipline_name?></h1>
				<div class="heading" >ELECTRONIC SIGNATURE AUTHENTICITY AGREEMENT</div>
				<div class="paragraph">
					<p>
						<span style="float:left;">I, <input class="form-control" name="aes_em_name" value="<?php echo $aes_info->aes_em_name?>"/>, 
						understand that <?php echo $discipline_name?>(“Agency”) employees, contractors and physicians may use electronic signatures on all computergenerateddocumentation “Documentation”. An electronic signature shall serve asauthentication on patient record documents and other Agency documents generated inHHCentre (“Application”).I acknowledge my use of the Electronic Signature Password (“ESP”) and my Login(“Login”) shall serve as my binding legal signature for the purpose of computerizedmedical records and other Documentation for Agency purposes.
					</p>
					<p>I understand that the Agency Administrator shall issue each employee a unique Login,system password for authentication, and initial ESP.</p>
					<p>I understand that the Agency may require scheduled resets of the ESP as directed byAgency policy. The Agency shall also have the ability to reset the password at its owndiscretion. I further understand that the ESP may be reset at my discretion givencompliance to Agency policy.</p>
					<p>I understand that prior to submitting Documentation to the Agency, I shall review andauthenticate, by use of electronic signature, my Documentation on the field-based oroffice computer.</p>
					<p>I understand that certain Documentation may not require electronic signature untilrequired information has been obtained.</p>
					<p>I understand that I shall not divulge my login, login password, and ESP, and that I mustexit the Application at the end of each working day, at the completion of work, andwhenever the computer is not in my immediate possession.I shall type in, rather than save, the login password that allows me access to theApplication, and my ESP.I understand further that violation of Agency policy pertaining to security and confidentiality of patient information are grounds for suspension and/or termination of employment/contract.</p>
				</div>
			</div>
			
			<div class="row">
				<div class="col-sm-4">
                                 	
					<img id="aes_esign" src="<?php echo $rn_info->signature; ?>" style="max-width:100%;" >
					<p>Employee/Contractor/Physician Signature</p>
				</div>
				<div class="col-sm-4"></div>
				<div class="col-sm-4">
                                        	 <img src="<?php
                                if (!empty($admin_info->esignature)) {
                                    echo $admin_info->esignature;
                                }
                                ?>"/>	
					
					<p>Administrator Signature</p>
				</div>
				
			</div>
			
			<div class="row">
				<div class="col-sm-4">
					<input class="form-control" name="aes_e_name" value="<?php echo $aes_info->aes_e_name?>"/>
					<p>Print Employee Name</p>
				</div>
				<div class="col-sm-4"></div>
				<div class="col-sm-4">
					<input class="form-control" name="aes_a_name" value="<?php echo $aes_info->aes_a_name?>"/>
					<p>Print Administrator Name</p>
				</div>
				
			</div>
			
			<div class="row">
				<div class="col-sm-4">
					<input name="aes_e_date" value="<?php echo $aes_info->aes_e_date?>" type="date" class="form-control"/>
					<p>Date</p>
				</div>
				<div class="col-sm-4"></div>
				<div class="col-sm-4">
					<input name="aes_a_date" value="<?php echo $aes_info->aes_a_date?>" type="date" class="form-control"/>
					<p>Date</p>
				</div>
				
			</div>
		</div>
		
    </form>
	<button id="btn_mhr_save" onclick="callfunc()" type="button" class="btn btn-primary btn-block" style="width: 20%; float: right;">Next</button>
</div>
<br />
<br />
<br />
<script>
    $.fn.serializeObject = function(){
    var o = {};
    var a = this.serializeArray();
    $.each(a, function() {
        if (o[this.name] !== undefined) {
            if (!o[this.name].push) {
                o[this.name] = [o[this.name]];
            }
            o[this.name].push(this.value || '');
        } else {
            o[this.name] = this.value || '';
        }
    });
    return o;
};

function callfunc(){ 
	$('#aes_form').val(JSON.stringify($('form.aesform').serializeObject()));
	$("#myModali9").hide();
	return false;
}
</script>